import { ISoundItem } from '../store';

const sounds = [
  {
    group: 'Locations',
    icon: 'fa-basketball',
    variantName: 'Basketball game',
    sound: 'Basketball court',
    asset: require('../assets/audio/Locations/Basketball court_fa-basketball/Basketball game.mp3'),
    free: true,
  },
  {
    group: 'Locations',
    icon: 'fa-basketball',
    variantName: 'Basketball game 2',
    sound: 'Basketball court',
    asset: require('../assets/audio/Locations/Basketball court_fa-basketball/Basketball game 2.mp3'),
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-basketball',
    variantName: 'Basketball training',
    sound: 'Basketball court',
    asset: require('../assets/audio/Locations/Basketball court_fa-basketball/Basketball training.mp3'),
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-water',
    variantName: 'Beach',
    sound: 'Waves',
    asset: require('../assets/audio/Background/Waves_fa-water/Beach.mp3'),
    free: true,
  },
  {
    group: 'Background',
    icon: 'fa-water',
    variantName: 'Beach 2',
    sound: 'Waves',
    asset: require('../assets/audio/Background/Waves_fa-water/Beach 2.mp3'),
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-water',
    variantName: 'Beach 3',
    sound: 'Waves',
    asset: require('../assets/audio/Background/Waves_fa-water/Beach 3.mp3'),
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-dove',
    variantName: 'Birdsong 1',
    sound: 'Birdsong',
    asset: require('../assets/audio/Background/Birdsong_fa-dove/Birdsong 1.mp3'),
    free: true,
  },
  {
    group: 'Background',
    icon: 'fa-dove',
    variantName: 'Birdsong 2',
    sound: 'Birdsong',
    asset: require('../assets/audio/Background/Birdsong_fa-dove/Birdsong 2.mp3'),
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-dove',
    variantName: 'Birdsong 3',
    sound: 'Birdsong',
    asset: require('../assets/audio/Background/Birdsong_fa-dove/Birdsong 3.mp3'),
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-dove',
    variantName: 'Birdsong 4',
    sound: 'Birdsong',
    asset: require('../assets/audio/Background/Birdsong_fa-dove/Birdsong 4.mp3'),
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-fire',
    variantName: 'Bonfire 1',
    sound: 'Bonfire',
    asset: require('../assets/audio/Background/Bonfire_fa-fire/Bonfire 1.mp3'),
    free: true,
  },
  {
    group: 'Background',
    icon: 'fa-fire',
    variantName: 'Bonfire 2',
    sound: 'Bonfire',
    asset: require('../assets/audio/Background/Bonfire_fa-fire/Bonfire 2.mp3'),
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-fire',
    variantName: 'Bonfire 3',
    sound: 'Bonfire',
    asset: require('../assets/audio/Background/Bonfire_fa-fire/Bonfire 3.mp3'),
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-fire',
    variantName: 'Bonfire 4',
    sound: 'Bonfire',
    asset: require('../assets/audio/Background/Bonfire_fa-fire/Bonfire 4.mp3'),
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-fire',
    variantName: 'Bonfire 5',
    sound: 'Bonfire',
    asset: require('../assets/audio/Background/Bonfire_fa-fire/Bonfire 5.mp3'),
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-face-nose-steam',
    variantName: 'Breathe',
    sound: 'Breath',
    asset: require('../assets/audio/Others/Breath_fa-face-nose-steam/Breathe.mp3'),
    free: true,
  },
  {
    group: 'Others',
    icon: 'fa-face-nose-steam',
    variantName: 'Breathe 3',
    sound: 'Breath',
    asset: require('../assets/audio/Others/Breath_fa-face-nose-steam/Breathe 3.mp3'),
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-face-nose-steam',
    variantName: 'Breathe(1)',
    sound: 'Breath',
    asset: require('../assets/audio/Others/Breath_fa-face-nose-steam/Breathe(1).mp3'),
    free: false,
  },
  {
    group: 'Color noise',
    icon: 'fa-volume',
    variantName: 'Brown Noise',
    sound: 'Brown noise',
    asset: require('../assets/audio/Color noise/Brown noise_fa-volume/Brown Noise.mp3'),
    free: true,
  },
  {
    group: 'Tweak',
    icon: 'fa-cauldron',
    variantName: 'Bubbles',
    sound: 'Bubbles',
    asset: require('../assets/audio/Tweak/Bubbles_fa-cauldron/Bubbles.mp3'),
    free: true,
  },
  {
    group: 'Tweak',
    icon: 'fa-cauldron',
    variantName: 'Bubbles 2',
    sound: 'Bubbles',
    asset: require('../assets/audio/Tweak/Bubbles_fa-cauldron/Bubbles 2.mp3'),
    free: false,
  },
  {
    group: 'Tweak',
    icon: 'fa-cauldron',
    variantName: 'Bubbles 3',
    sound: 'Bubbles',
    asset: require('../assets/audio/Tweak/Bubbles_fa-cauldron/Bubbles 3.mp3'),
    free: false,
  },
  {
    group: 'Tweak',
    icon: 'fa-cauldron',
    variantName: 'Bubbles 4',
    sound: 'Bubbles',
    asset: require('../assets/audio/Tweak/Bubbles_fa-cauldron/Bubbles 4.mp3'),
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-plane',
    variantName: 'Cabin 1',
    sound: 'Plane',
    asset: require('../assets/audio/Locations/Plane_fa-plane/Cabin 1.mp3'),
    free: true,
  },
  {
    group: 'Locations',
    icon: 'fa-plane',
    variantName: 'Cabin 2',
    sound: 'Plane',
    asset: require('../assets/audio/Locations/Plane_fa-plane/Cabin 2.mp3'),
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-plane',
    variantName: 'Cabin 3',
    sound: 'Plane',
    asset: require('../assets/audio/Locations/Plane_fa-plane/Cabin 3.mp3'),
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-mug-saucer',
    variantName: 'Cafe (English speech)',
    sound: 'Cafe',
    asset: require('../assets/audio/Locations/Cafe_fa-mug-saucer/Cafe (English speech).mp3'),
    free: true,
  },
  {
    group: 'Locations',
    icon: 'fa-mug-saucer',
    variantName: 'Cafe (Russian speech)',
    sound: 'Cafe',
    asset: require('../assets/audio/Locations/Cafe_fa-mug-saucer/Cafe (Russian speech).mp3'),
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-mug-saucer',
    variantName: 'Cafe 1',
    sound: 'Cafe',
    asset: require('../assets/audio/Locations/Cafe_fa-mug-saucer/Cafe 1.mp3'),
    free: false,
  },
  {
    group: 'ASMR',
    icon: 'fa-hands-clapping',
    variantName: 'Cardboard box',
    sound: 'Tapping',
    asset: require('../assets/audio/ASMR/Tapping_fa-hands-clapping/Cardboard box.mp3'),
    free: true,
  },
  {
    group: 'Background',
    icon: 'fa-road',
    variantName: 'Cars, trains',
    sound: 'Road',
    asset: require('../assets/audio/Background/Road_fa-road/Cars, trains.mp3'),
    free: true,
  },
  {
    group: 'Locations',
    icon: 'fa-bag-shopping',
    variantName: 'Cash machine',
    sound: 'Supermarket',
    asset: require('../assets/audio/Locations/Supermarket_fa-bag-shopping/Cash machine.mp3'),
    free: true,
  },
  {
    group: 'Tweak',
    icon: 'fa-cat',
    variantName: 'Cat purr',
    sound: 'Cat purr',
    asset: require('../assets/audio/Tweak/Cat purr_fa-cat/Cat purr.mp3'),
    free: true,
  },
  {
    group: 'Tweak',
    icon: 'fa-cat',
    variantName: 'Cat purr 2',
    sound: 'Cat purr',
    asset: require('../assets/audio/Tweak/Cat purr_fa-cat/Cat purr 2.mp3'),
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-bars-staggered',
    variantName: 'Cave stream',
    sound: 'Stream',
    asset: require('../assets/audio/Background/Stream_fa-bars-staggered/Cave stream.mp3'),
    free: true,
  },
  {
    group: 'Tweak',
    icon: 'fa-fan',
    variantName: 'Ceiling fan',
    sound: 'Ceiling fan',
    asset: require('../assets/audio/Tweak/Ceiling fan_fa-fan/Ceiling fan.mp3'),
    free: true,
  },
  {
    group: 'Tweak',
    icon: 'fa-fan',
    variantName: 'Ceiling fan 2',
    sound: 'Ceiling fan',
    asset: require('../assets/audio/Tweak/Ceiling fan_fa-fan/Ceiling fan 2.mp3'),
    free: false,
  },
  {
    group: 'Tweak',
    icon: 'fa-cookie-bite',
    variantName: 'Chewing',
    sound: 'Potato chips',
    asset: require('../assets/audio/Tweak/Potato chips_fa-cookie-bite/Chewing.mp3'),
    free: true,
  },
  {
    group: 'Tweak',
    icon: 'fa-cookie-bite',
    variantName: 'Chewing 2',
    sound: 'Potato chips',
    asset: require('../assets/audio/Tweak/Potato chips_fa-cookie-bite/Chewing 2.mp3'),
    free: false,
  },
  {
    group: 'Tweak',
    icon: 'fa-cookie-bite',
    variantName: 'Chewing 3',
    sound: 'Potato chips',
    asset: require('../assets/audio/Tweak/Potato chips_fa-cookie-bite/Chewing 3.mp3'),
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-feather',
    variantName: 'Chicken coop',
    sound: 'Chicken coop',
    asset: require('../assets/audio/Locations/Chicken coop_fa-feather/Chicken coop.mp3'),
    free: true,
  },
  {
    group: 'Locations',
    icon: 'fa-feather',
    variantName: 'Chicken coop 1',
    sound: 'Chicken coop',
    asset: require('../assets/audio/Locations/Chicken coop_fa-feather/Chicken coop 1.mp3'),
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-feather',
    variantName: 'Chickens',
    sound: 'Chicken coop',
    asset: require('../assets/audio/Locations/Chicken coop_fa-feather/Chickens.mp3'),
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-bell',
    variantName: 'Chime',
    sound: 'Bells',
    asset: require('../assets/audio/Locations/Bells_fa-bell/Chime.mp3'),
    free: true,
  },
  {
    group: 'Locations',
    icon: 'fa-bell',
    variantName: 'Chime 2',
    sound: 'Bells',
    asset: require('../assets/audio/Locations/Bells_fa-bell/Chime 2.mp3'),
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-bell',
    variantName: 'Chime 3',
    sound: 'Bells',
    asset: require('../assets/audio/Locations/Bells_fa-bell/Chime 3.mp3'),
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-bell',
    variantName: 'Chime 4',
    sound: 'Bells',
    asset: require('../assets/audio/Locations/Bells_fa-bell/Chime 4.mp3'),
    free: false,
  },
  {
    group: 'Tweak',
    icon: 'fa-clock',
    variantName: 'Chimes',
    sound: 'Clocks',
    asset: require('../assets/audio/Tweak/Clocks_fa-clock/Chimes.mp3'),
    free: true,
  },
  {
    group: 'Tweak',
    icon: 'fa-clock',
    variantName: 'Clock tower',
    sound: 'Clocks',
    asset: require('../assets/audio/Tweak/Clocks_fa-clock/Clock tower.mp3'),
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-water',
    variantName: 'Coastal cave',
    sound: 'Waves',
    asset: require('../assets/audio/Background/Waves_fa-water/Coastal cave.mp3'),
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-mug-saucer',
    variantName: 'Coffee machine',
    sound: 'Cafe',
    asset: require('../assets/audio/Locations/Cafe_fa-mug-saucer/Coffee machine.mp3'),
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-house',
    variantName: 'Country life',
    sound: 'Country life',
    asset: require('../assets/audio/Background/Country life_fa-house/Country life.mp3'),
    free: true,
  },
  {
    group: 'Background',
    icon: 'fa-house',
    variantName: 'Country life 2',
    sound: 'Country life',
    asset: require('../assets/audio/Background/Country life_fa-house/Country life 2.mp3'),
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-house',
    variantName: 'Country life 3',
    sound: 'Country life',
    asset: require('../assets/audio/Background/Country life_fa-house/Country life 3.mp3'),
    free: false,
  },
  {
    group: 'Tweak',
    icon: 'fa-octopus-deploy',
    variantName: 'Depth',
    sound: 'Deep sea',
    asset: require('../assets/audio/Tweak/Deep sea_fa-octopus-deploy/Depth.mp3'),
    free: true,
  },
  {
    group: 'Tweak',
    icon: 'fa-octopus-deploy',
    variantName: 'Depth 2',
    sound: 'Deep sea',
    asset: require('../assets/audio/Tweak/Deep sea_fa-octopus-deploy/Depth 2.mp3'),
    free: false,
  },
  {
    group: 'Tweak',
    icon: 'fa-octopus-deploy',
    variantName: 'Depth 3',
    sound: 'Deep sea',
    asset: require('../assets/audio/Tweak/Deep sea_fa-octopus-deploy/Depth 3.mp3'),
    free: false,
  },
  {
    group: 'Tweak',
    icon: 'fa-octopus-deploy',
    variantName: 'Depth 4',
    sound: 'Deep sea',
    asset: require('../assets/audio/Tweak/Deep sea_fa-octopus-deploy/Depth 4.mp3'),
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-wind',
    variantName: 'Desert',
    sound: 'Wind',
    asset: require('../assets/audio/Background/Wind_fa-wind/Desert.mp3'),
    free: true,
  },
  {
    group: 'ASMR',
    variantName: 'Ear massage',
    sound: 'Triggers',
    asset: require('../assets/audio/ASMR/Triggers/Ear massage.mp3'),
    free: true,
  },
  {
    group: 'Others',
    icon: 'fa-engine',
    variantName: 'Engine',
    sound: 'Engine',
    asset: require('../assets/audio/Others/Engine_fa-engine/Engine.mp3'),
    free: true,
  },
  {
    group: 'Others',
    icon: 'fa-engine',
    variantName: 'Engine 2',
    sound: 'Engine',
    asset: require('../assets/audio/Others/Engine_fa-engine/Engine 2.mp3'),
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-engine',
    variantName: 'Engine 3',
    sound: 'Engine',
    asset: require('../assets/audio/Others/Engine_fa-engine/Engine 3.mp3'),
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-engine',
    variantName: 'Engine 4',
    sound: 'Engine',
    asset: require('../assets/audio/Others/Engine_fa-engine/Engine 4.mp3'),
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-church',
    variantName: 'English chants',
    sound: 'Chants',
    asset: require('../assets/audio/Locations/Chants_fa-church/English chants.mp3'),
    free: true,
  },
  {
    group: 'Locations',
    icon: 'fa-church',
    variantName: 'English chants to organ',
    sound: 'Chants',
    asset: require('../assets/audio/Locations/Chants_fa-church/English chants to organ.mp3'),
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-train-subway',
    variantName: 'Escalator',
    sound: 'Underground',
    asset: require('../assets/audio/Locations/Underground_fa-train-subway/Escalator.mp3'),
    free: true,
  },
  {
    group: 'ASMR',
    icon: 'fa-scissors',
    variantName: 'Face cleaning',
    sound: 'Barbershop',
    asset: require('../assets/audio/ASMR/Barbershop_fa-scissors/Face cleaning.mp3'),
    free: true,
  },
  {
    group: 'Background',
    icon: 'fa-wind',
    variantName: 'Far',
    sound: 'Wind',
    asset: require('../assets/audio/Background/Wind_fa-wind/Far.mp3'),
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-tractor',
    variantName: 'Farm',
    sound: 'Farm',
    asset: require('../assets/audio/Locations/Farm_fa-tractor/Farm.mp3'),
    free: true,
  },
  {
    group: 'Locations',
    icon: 'fa-tractor',
    variantName: 'Farm 2',
    sound: 'Farm',
    asset: require('../assets/audio/Locations/Farm_fa-tractor/Farm 2.mp3'),
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-tractor',
    variantName: 'Farm 3',
    sound: 'Farm',
    asset: require('../assets/audio/Locations/Farm_fa-tractor/Farm 3.mp3'),
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-tractor',
    variantName: 'Farm 4',
    sound: 'Farm',
    asset: require('../assets/audio/Locations/Farm_fa-tractor/Farm 4.mp3'),
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-comments',
    variantName: 'Female conversation (English speech)',
    sound: 'Conversations',
    asset: require('../assets/audio/Locations/Conversations_fa-comments/Female conversation (English speech).mp3'),
    free: true,
  },
  {
    group: 'Background',
    icon: 'fa-fire',
    variantName: 'Fireplace',
    sound: 'Bonfire',
    asset: require('../assets/audio/Background/Bonfire_fa-fire/Fireplace.mp3'),
    free: false,
  },
  {
    group: 'Tweak',
    variantName: 'Fireworks ',
    sound: 'Fireworks',
    asset: require('../assets/audio/Tweak/Fireworks/Fireworks .mp3'),
    free: true,
  },
  {
    group: 'Tweak',
    variantName: 'Fireworks 2',
    sound: 'Fireworks',
    asset: require('../assets/audio/Tweak/Fireworks/Fireworks 2.mp3'),
    free: false,
  },
  {
    group: 'Tweak',
    variantName: 'Fireworks 3',
    sound: 'Fireworks',
    asset: require('../assets/audio/Tweak/Fireworks/Fireworks 3.mp3'),
    free: false,
  },
  {
    group: 'ASMR',
    variantName: 'Fizzy',
    sound: 'Triggers',
    asset: require('../assets/audio/ASMR/Triggers/Fizzy.mp3'),
    free: false,
  },
  {
    group: 'ASMR',
    variantName: 'Foam',
    sound: 'Triggers',
    asset: require('../assets/audio/ASMR/Triggers/Foam.mp3'),
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-tree',
    variantName: 'Forest 1',
    sound: 'Forest',
    asset: require('../assets/audio/Background/Forest_fa-tree/Forest 1.mp3'),
    free: true,
  },
  {
    group: 'Background',
    icon: 'fa-tree',
    variantName: 'Forest 2',
    sound: 'Forest',
    asset: require('../assets/audio/Background/Forest_fa-tree/Forest 2.mp3'),
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-tree',
    variantName: 'Forest 3',
    sound: 'Forest',
    asset: require('../assets/audio/Background/Forest_fa-tree/Forest 3.mp3'),
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-tree',
    variantName: 'Forest 4',
    sound: 'Forest',
    asset: require('../assets/audio/Background/Forest_fa-tree/Forest 4.mp3'),
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-tree',
    variantName: 'Forest 5',
    sound: 'Forest',
    asset: require('../assets/audio/Background/Forest_fa-tree/Forest 5.mp3'),
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-comments',
    variantName: 'French speech',
    sound: 'Conversations',
    asset: require('../assets/audio/Locations/Conversations_fa-comments/French speech.mp3'),
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-frog',
    variantName: 'Frogs and cicadas',
    sound: 'Frog',
    asset: require('../assets/audio/Background/Frog_fa-frog/Frogs and cicadas.mp3'),
    free: true,
  },
  {
    group: 'Background',
    icon: 'fa-frog',
    variantName: 'Frogs and cicadas 2',
    sound: 'Frog',
    asset: require('../assets/audio/Background/Frog_fa-frog/Frogs and cicadas 2.mp3'),
    free: false,
  },
  {
    group: 'Tweak',
    icon: 'fa-user-hair',
    variantName: 'Hair dryer',
    sound: 'Hair dryer',
    asset: require('../assets/audio/Tweak/Hair dryer_fa-user-hair/Hair dryer.mp3'),
    free: true,
  },
  {
    group: 'Tweak',
    icon: 'fa-user-hair',
    variantName: 'Hair dryer 2',
    sound: 'Hair dryer',
    asset: require('../assets/audio/Tweak/Hair dryer_fa-user-hair/Hair dryer 2.mp3'),
    free: false,
  },
  {
    group: 'Tweak',
    icon: 'fa-user-hair',
    variantName: 'Hair dryer 3',
    sound: 'Hair dryer',
    asset: require('../assets/audio/Tweak/Hair dryer_fa-user-hair/Hair dryer 3.mp3'),
    free: false,
  },
  {
    group: 'ASMR',
    icon: 'fa-scissors',
    variantName: 'Haircut',
    sound: 'Barbershop',
    asset: require('../assets/audio/ASMR/Barbershop_fa-scissors/Haircut.mp3'),
    free: false,
  },
  {
    group: 'ASMR',
    icon: 'fa-scissors',
    variantName: 'Haircut 2',
    sound: 'Barbershop',
    asset: require('../assets/audio/ASMR/Barbershop_fa-scissors/Haircut 2.mp3'),
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-wind',
    variantName: 'Howling',
    sound: 'Wind',
    asset: require('../assets/audio/Background/Wind_fa-wind/Howling.mp3'),
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-plane',
    variantName: 'In the plane',
    sound: 'Plane',
    asset: require('../assets/audio/Locations/Plane_fa-plane/In the plane.mp3'),
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-plane',
    variantName: 'In the plane 2',
    sound: 'Plane',
    asset: require('../assets/audio/Locations/Plane_fa-plane/In the plane 2.mp3'),
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-train',
    variantName: 'Inside the train',
    sound: 'Train',
    asset: require('../assets/audio/Locations/Train_fa-train/Inside the train.mp3'),
    free: true,
  },
  {
    group: 'Locations',
    icon: 'fa-train',
    variantName: 'Inside the train 2',
    sound: 'Train',
    asset: require('../assets/audio/Locations/Train_fa-train/Inside the train 2.mp3'),
    free: false,
  },
  {
    group: 'Tweak',
    icon: 'fa-print',
    variantName: 'Jet printer',
    sound: 'Printer',
    asset: require('../assets/audio/Tweak/Printer_fa-print/Jet printer.mp3'),
    free: true,
  },
  {
    group: 'Tweak',
    icon: 'fa-print',
    variantName: 'Jet printer 2',
    sound: 'Printer',
    asset: require('../assets/audio/Tweak/Printer_fa-print/Jet printer 2.mp3'),
    free: false,
  },
  {
    group: 'Tweak',
    icon: 'fa-keyboard',
    variantName: 'Keyboard',
    sound: 'Keyboard',
    asset: require('../assets/audio/Tweak/Keyboard_fa-keyboard/Keyboard.mp3'),
    free: true,
  },
  {
    group: 'Tweak',
    icon: 'fa-keyboard',
    variantName: 'Keyboard 2',
    sound: 'Keyboard',
    asset: require('../assets/audio/Tweak/Keyboard_fa-keyboard/Keyboard 2.mp3'),
    free: false,
  },
  {
    group: 'ASMR',
    icon: 'fa-hands-clapping',
    variantName: 'Leater cover',
    sound: 'Tapping',
    asset: require('../assets/audio/ASMR/Tapping_fa-hands-clapping/Leater cover.mp3'),
    free: false,
  },
  {
    group: 'ASMR',
    icon: 'fa-hands-clapping',
    variantName: 'Leather pillow',
    sound: 'Tapping',
    asset: require('../assets/audio/ASMR/Tapping_fa-hands-clapping/Leather pillow.mp3'),
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-wind',
    variantName: 'Light',
    sound: 'Wind',
    asset: require('../assets/audio/Background/Wind_fa-wind/Light.mp3'),
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-volcano',
    variantName: 'Magma',
    sound: 'Magma',
    asset: require('../assets/audio/Others/Magma_fa-volcano/Magma.mp3'),
    free: true,
  },
  {
    group: 'Others',
    icon: 'fa-volcano',
    variantName: 'Magma 2',
    sound: 'Magma',
    asset: require('../assets/audio/Others/Magma_fa-volcano/Magma 2.mp3'),
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-volcano',
    variantName: 'Magma 3',
    sound: 'Magma',
    asset: require('../assets/audio/Others/Magma_fa-volcano/Magma 3.mp3'),
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-comments',
    variantName: 'Man at the bar (English speech',
    sound: 'Conversations',
    asset: require('../assets/audio/Locations/Conversations_fa-comments/Man at the bar (English speech.mp3'),
    free: false,
  },
  {
    group: 'Tweak',
    icon: 'fa-print',
    variantName: 'Matrix printer',
    sound: 'Printer',
    asset: require('../assets/audio/Tweak/Printer_fa-print/Matrix printer.mp3'),
    free: false,
  },
  {
    group: 'Tweak',
    icon: 'fa-print',
    variantName: 'Matrix printer 2',
    sound: 'Printer',
    asset: require('../assets/audio/Tweak/Printer_fa-print/Matrix printer 2.mp3'),
    free: false,
  },
  {
    group: 'Tweak',
    icon: 'fa-clock',
    variantName: 'Mechanic timer',
    sound: 'Clocks',
    asset: require('../assets/audio/Tweak/Clocks_fa-clock/Mechanic timer.mp3'),
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-wind',
    variantName: 'Medium',
    sound: 'Wind',
    asset: require('../assets/audio/Background/Wind_fa-wind/Medium.mp3'),
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-wind',
    variantName: 'Medium 2',
    sound: 'Wind',
    asset: require('../assets/audio/Background/Wind_fa-wind/Medium 2.mp3'),
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-comments',
    variantName: 'Men at the bar (German speech)',
    sound: 'Conversations',
    asset: require('../assets/audio/Locations/Conversations_fa-comments/Men at the bar (German speech).mp3'),
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-bars-staggered',
    variantName: 'Mountain creek',
    sound: 'Stream',
    asset: require('../assets/audio/Background/Stream_fa-bars-staggered/Mountain creek.mp3'),
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-comments',
    variantName: 'Neighbors (English speech)',
    sound: 'Conversations',
    asset: require('../assets/audio/Locations/Conversations_fa-comments/Neighbors (English speech).mp3'),
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-train-subway',
    variantName: 'New york subway',
    sound: 'Underground',
    asset: require('../assets/audio/Locations/Underground_fa-train-subway/New york subway.mp3'),
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-moon',
    variantName: 'Night',
    sound: 'Night',
    asset: require('../assets/audio/Background/Night_fa-moon/Night.mp3'),
    free: true,
  },
  {
    group: 'Background',
    icon: 'fa-moon',
    variantName: 'Night 2',
    sound: 'Night',
    asset: require('../assets/audio/Background/Night_fa-moon/Night 2.mp3'),
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-moon',
    variantName: 'Night in city',
    sound: 'Night',
    asset: require('../assets/audio/Background/Night_fa-moon/Night in city.mp3'),
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-moon',
    variantName: 'Night in city 2',
    sound: 'Night',
    asset: require('../assets/audio/Background/Night_fa-moon/Night in city 2.mp3'),
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-comments',
    variantName: 'Night talk',
    sound: 'Conversations',
    asset: require('../assets/audio/Locations/Conversations_fa-comments/Night talk.mp3'),
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-bag-shopping',
    variantName: 'Old cash machine',
    sound: 'Supermarket',
    asset: require('../assets/audio/Locations/Supermarket_fa-bag-shopping/Old cash machine.mp3'),
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-wind',
    variantName: 'Ominous',
    sound: 'Wind',
    asset: require('../assets/audio/Background/Wind_fa-wind/Ominous.mp3'),
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-person-walking',
    variantName: 'On earth',
    sound: 'Walk',
    asset: require('../assets/audio/Others/Walk_fa-person-walking/On earth.mp3'),
    free: true,
  },
  {
    group: 'Others',
    icon: 'fa-person-walking',
    variantName: 'On earth 2',
    sound: 'Walk',
    asset: require('../assets/audio/Others/Walk_fa-person-walking/On earth 2.mp3'),
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-person-walking',
    variantName: 'On earth 3',
    sound: 'Walk',
    asset: require('../assets/audio/Others/Walk_fa-person-walking/On earth 3.mp3'),
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-person-walking',
    variantName: 'On earth 4',
    sound: 'Walk',
    asset: require('../assets/audio/Others/Walk_fa-person-walking/On earth 4.mp3'),
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-person-walking',
    variantName: 'On grass',
    sound: 'Walk',
    asset: require('../assets/audio/Others/Walk_fa-person-walking/On grass.mp3'),
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-person-walking',
    variantName: 'On grass 2',
    sound: 'Walk',
    asset: require('../assets/audio/Others/Walk_fa-person-walking/On grass 2.mp3'),
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-person-walking',
    variantName: 'On grass 3',
    sound: 'Walk',
    asset: require('../assets/audio/Others/Walk_fa-person-walking/On grass 3.mp3'),
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-person-walking',
    variantName: 'On leaves',
    sound: 'Walk',
    asset: require('../assets/audio/Others/Walk_fa-person-walking/On leaves.mp3'),
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-person-walking',
    variantName: 'On leaves 2',
    sound: 'Walk',
    asset: require('../assets/audio/Others/Walk_fa-person-walking/On leaves 2.mp3'),
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-person-walking',
    variantName: 'On leaves 3',
    sound: 'Walk',
    asset: require('../assets/audio/Others/Walk_fa-person-walking/On leaves 3.mp3'),
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-person-walking',
    variantName: 'On sand',
    sound: 'Walk',
    asset: require('../assets/audio/Others/Walk_fa-person-walking/On sand.mp3'),
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-person-walking',
    variantName: 'On sand 2',
    sound: 'Walk',
    asset: require('../assets/audio/Others/Walk_fa-person-walking/On sand 2.mp3'),
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-person-walking',
    variantName: 'On sand 3',
    sound: 'Walk',
    asset: require('../assets/audio/Others/Walk_fa-person-walking/On sand 3.mp3'),
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-person-walking',
    variantName: 'On snow',
    sound: 'Walk',
    asset: require('../assets/audio/Others/Walk_fa-person-walking/On snow.mp3'),
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-person-walking',
    variantName: 'On snow 2',
    sound: 'Walk',
    asset: require('../assets/audio/Others/Walk_fa-person-walking/On snow 2.mp3'),
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-person-walking',
    variantName: 'On snow 3',
    sound: 'Walk',
    asset: require('../assets/audio/Others/Walk_fa-person-walking/On snow 3.mp3'),
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-person-walking',
    variantName: 'On snow 4',
    sound: 'Walk',
    asset: require('../assets/audio/Others/Walk_fa-person-walking/On snow 4.mp3'),
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-person-walking',
    variantName: 'On snow 5',
    sound: 'Walk',
    asset: require('../assets/audio/Others/Walk_fa-person-walking/On snow 5.mp3'),
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-person-walking',
    variantName: 'On snow 6',
    sound: 'Walk',
    asset: require('../assets/audio/Others/Walk_fa-person-walking/On snow 6.mp3'),
    free: false,
  },
  {
    group: 'Color noise',
    icon: 'fa-waveform',
    variantName: 'Pink noise',
    sound: 'Pink noise',
    asset: require('../assets/audio/Color noise/Pink noise_fa-waveform/Pink noise.mp3'),
    free: true,
  },
  {
    group: 'Locations',
    icon: 'fa-plane',
    variantName: 'Plane',
    sound: 'Plane',
    asset: require('../assets/audio/Locations/Plane_fa-plane/Plane.mp3'),
    free: false,
  },
  {
    group: 'ASMR',
    icon: 'fa-hands-clapping',
    variantName: 'Plastic',
    sound: 'Tapping',
    asset: require('../assets/audio/ASMR/Tapping_fa-hands-clapping/Plastic.mp3'),
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-puzzle-piece',
    variantName: 'Playground',
    sound: 'Playground',
    asset: require('../assets/audio/Locations/Playground_fa-puzzle-piece/Playground.mp3'),
    free: true,
  },
  {
    group: 'Locations',
    icon: 'fa-puzzle-piece',
    variantName: 'Playground 2',
    sound: 'Playground',
    asset: require('../assets/audio/Locations/Playground_fa-puzzle-piece/Playground 2.mp3'),
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-puzzle-piece',
    variantName: 'Playground 3',
    sound: 'Playground',
    asset: require('../assets/audio/Locations/Playground_fa-puzzle-piece/Playground 3.mp3'),
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-puzzle-piece',
    variantName: 'Playground 4',
    sound: 'Playground',
    asset: require('../assets/audio/Locations/Playground_fa-puzzle-piece/Playground 4.mp3'),
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-sailboat',
    variantName: 'Powerboat',
    sound: 'Boat',
    asset: require('../assets/audio/Others/Boat_fa-sailboat/Powerboat.mp3'),
    free: true,
  },
  {
    group: 'Others',
    icon: 'fa-sailboat',
    variantName: 'Powerboat 2',
    sound: 'Boat',
    asset: require('../assets/audio/Others/Boat_fa-sailboat/Powerboat 2.mp3'),
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-mosque',
    variantName: 'Prayer',
    sound: 'Mosque',
    asset: require('../assets/audio/Locations/Mosque_fa-mosque/Prayer.mp3'),
    free: true,
  },
  {
    group: 'Locations',
    icon: 'fa-train',
    variantName: 'Railway station',
    sound: 'Train',
    asset: require('../assets/audio/Locations/Train_fa-train/Railway station.mp3'),
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-cloud-showers-heavy',
    variantName: 'Rain',
    sound: 'Rain',
    asset: require('../assets/audio/Background/Rain_fa-cloud-showers-heavy/Rain.mp3'),
    free: true,
  },
  {
    group: 'Background',
    icon: 'fa-cloud-showers-heavy',
    variantName: 'Rain 2',
    sound: 'Rain',
    asset: require('../assets/audio/Background/Rain_fa-cloud-showers-heavy/Rain 2.mp3'),
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-cloud-showers-heavy',
    variantName: 'Rain 3',
    sound: 'Rain',
    asset: require('../assets/audio/Background/Rain_fa-cloud-showers-heavy/Rain 3.mp3'),
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-cloud-showers-heavy',
    variantName: 'Rain on the tent',
    sound: 'Rain',
    asset: require('../assets/audio/Background/Rain_fa-cloud-showers-heavy/Rain on the tent.mp3'),
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-cloud-showers-heavy',
    variantName: 'Rain over un umbrella',
    sound: 'Rain',
    asset: require('../assets/audio/Background/Rain_fa-cloud-showers-heavy/Rain over un umbrella.mp3'),
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-cloud-showers-heavy',
    variantName: 'Rain with thunderstorm',
    sound: 'Rain',
    asset: require('../assets/audio/Background/Rain_fa-cloud-showers-heavy/Rain with thunderstorm.mp3'),
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-road',
    variantName: 'Road',
    sound: 'Road',
    asset: require('../assets/audio/Background/Road_fa-road/Road.mp3'),
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-road',
    variantName: 'Road 2',
    sound: 'Road',
    asset: require('../assets/audio/Background/Road_fa-road/Road 2.mp3'),
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-water',
    variantName: 'Rocky coast',
    sound: 'Waves',
    asset: require('../assets/audio/Background/Waves_fa-water/Rocky coast.mp3'),
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-sailboat',
    variantName: 'Rowing boat',
    sound: 'Boat',
    asset: require('../assets/audio/Others/Boat_fa-sailboat/Rowing boat.mp3'),
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-sailboat',
    variantName: 'Rowing boat 2',
    sound: 'Boat',
    asset: require('../assets/audio/Others/Boat_fa-sailboat/Rowing boat 2.mp3'),
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-church',
    variantName: 'Russian chants',
    sound: 'Chants',
    asset: require('../assets/audio/Locations/Chants_fa-church/Russian chants.mp3'),
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-fire',
    variantName: 'Smouldering coals',
    sound: 'Bonfire',
    asset: require('../assets/audio/Background/Bonfire_fa-fire/Smouldering coals.mp3'),
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-face-nose-steam',
    variantName: 'Sniff',
    sound: 'Breath',
    asset: require('../assets/audio/Others/Breath_fa-face-nose-steam/Sniff.mp3'),
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-face-nose-steam',
    variantName: 'Sniff 2',
    sound: 'Breath',
    asset: require('../assets/audio/Others/Breath_fa-face-nose-steam/Sniff 2.mp3'),
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-face-nose-steam',
    variantName: 'Snore',
    sound: 'Breath',
    asset: require('../assets/audio/Others/Breath_fa-face-nose-steam/Snore.mp3'),
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-road',
    variantName: 'Snowy road',
    sound: 'Road',
    asset: require('../assets/audio/Background/Road_fa-road/Snowy road.mp3'),
    free: false,
  },
  {
    group: 'Tweak',
    icon: 'fa-user-astronaut',
    variantName: 'Space',
    sound: 'Space',
    asset: require('../assets/audio/Tweak/Space_fa-user-astronaut/Space.mp3'),
    free: true,
  },
  {
    group: 'Tweak',
    icon: 'fa-user-astronaut',
    variantName: 'Space 2',
    sound: 'Space',
    asset: require('../assets/audio/Tweak/Space_fa-user-astronaut/Space 2.mp3'),
    free: false,
  },
  {
    group: 'Tweak',
    icon: 'fa-user-astronaut',
    variantName: 'Space 3',
    sound: 'Space',
    asset: require('../assets/audio/Tweak/Space_fa-user-astronaut/Space 3.mp3'),
    free: false,
  },
  {
    group: 'Tweak',
    icon: 'fa-user-astronaut',
    variantName: 'Space 4',
    sound: 'Space',
    asset: require('../assets/audio/Tweak/Space_fa-user-astronaut/Space 4.mp3'),
    free: false,
  },
  {
    group: 'Tweak',
    icon: 'fa-user-astronaut',
    variantName: 'Space 5',
    sound: 'Space',
    asset: require('../assets/audio/Tweak/Space_fa-user-astronaut/Space 5.mp3'),
    free: false,
  },
  {
    group: 'ASMR',
    variantName: 'Sponge',
    sound: 'Triggers',
    asset: require('../assets/audio/ASMR/Triggers/Sponge.mp3'),
    free: false,
  },
  {
    group: 'ASMR',
    icon: 'fa-scissors',
    variantName: 'Spraying',
    sound: 'Barbershop',
    asset: require('../assets/audio/ASMR/Barbershop_fa-scissors/Spraying.mp3'),
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-train-subway',
    variantName: 'St. Petersburg metro',
    sound: 'Underground',
    asset: require('../assets/audio/Locations/Underground_fa-train-subway/St. Petersburg metro.mp3'),
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-person-walking',
    variantName: 'Steps',
    sound: 'Walk',
    asset: require('../assets/audio/Others/Walk_fa-person-walking/Steps.mp3'),
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-person-walking',
    variantName: 'Steps 2',
    sound: 'Walk',
    asset: require('../assets/audio/Others/Walk_fa-person-walking/Steps 2.mp3'),
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-person-walking',
    variantName: 'Steps 3',
    sound: 'Walk',
    asset: require('../assets/audio/Others/Walk_fa-person-walking/Steps 3.mp3'),
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-person-walking',
    variantName: 'Steps on the carpet',
    sound: 'Walk',
    asset: require('../assets/audio/Others/Walk_fa-person-walking/Steps on the carpet.mp3'),
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-person-walking',
    variantName: 'Steps on the wood',
    sound: 'Walk',
    asset: require('../assets/audio/Others/Walk_fa-person-walking/Steps on the wood.mp3'),
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-person-walking',
    variantName: 'Steps on the wood 2',
    sound: 'Walk',
    asset: require('../assets/audio/Others/Walk_fa-person-walking/Steps on the wood 2.mp3'),
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-water',
    variantName: 'Storm',
    sound: 'Waves',
    asset: require('../assets/audio/Background/Waves_fa-water/Storm.mp3'),
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-bars-staggered',
    variantName: 'Stream',
    sound: 'Stream',
    asset: require('../assets/audio/Background/Stream_fa-bars-staggered/Stream.mp3'),
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-bars-staggered',
    variantName: 'Stream 2',
    sound: 'Stream',
    asset: require('../assets/audio/Background/Stream_fa-bars-staggered/Stream 2.mp3'),
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-bars-staggered',
    variantName: 'Stream 3',
    sound: 'Stream',
    asset: require('../assets/audio/Background/Stream_fa-bars-staggered/Stream 3.mp3'),
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-city',
    variantName: 'Street noise',
    sound: 'Street, city',
    asset: require('../assets/audio/Locations/Street, city_fa-city/Street noise.mp3'),
    free: true,
  },
  {
    group: 'Locations',
    icon: 'fa-city',
    variantName: 'Street noise 2',
    sound: 'Street, city',
    asset: require('../assets/audio/Locations/Street, city_fa-city/Street noise 2.mp3'),
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-wind',
    variantName: 'Strong',
    sound: 'Wind',
    asset: require('../assets/audio/Background/Wind_fa-wind/Strong.mp3'),
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-bag-shopping',
    variantName: 'Supermarket',
    sound: 'Supermarket',
    asset: require('../assets/audio/Locations/Supermarket_fa-bag-shopping/Supermarket.mp3'),
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-bag-shopping',
    variantName: 'Supermarket(1)',
    sound: 'Supermarket',
    asset: require('../assets/audio/Locations/Supermarket_fa-bag-shopping/Supermarket(1).mp3'),
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-person-swimming',
    variantName: 'Swim',
    sound: 'Swim',
    asset: require('../assets/audio/Others/Swim_fa-person-swimming/Swim.mp3'),
    free: true,
  },
  {
    group: 'Others',
    icon: 'fa-person-swimming',
    variantName: 'Swim 2',
    sound: 'Swim',
    asset: require('../assets/audio/Others/Swim_fa-person-swimming/Swim 2.mp3'),
    free: false,
  },
  {
    group: 'ASMR',
    variantName: 'TCHKTCHKTCHK',
    sound: 'Whisper',
    asset: require('../assets/audio/ASMR/Whisper/TCHKTCHKTCHK.mp3'),
    free: true,
  },
  {
    group: 'ASMR',
    variantName: 'TKTKTK',
    sound: 'Whisper',
    asset: require('../assets/audio/ASMR/Whisper/TKTKTK.mp3'),
    free: false,
  },
  {
    group: 'Tweak',
    icon: 'fa-fan-table',
    variantName: 'Table fan',
    sound: 'Table fan',
    asset: require('../assets/audio/Tweak/Table fan_fa-fan-table/Table fan.mp3'),
    free: true,
  },
  {
    group: 'Tweak',
    icon: 'fa-fan-table',
    variantName: 'Table fan 2',
    sound: 'Table fan',
    asset: require('../assets/audio/Tweak/Table fan_fa-fan-table/Table fan 2.mp3'),
    free: false,
  },
  {
    group: 'ASMR',
    variantName: 'Tapping',
    sound: 'Triggers',
    asset: require('../assets/audio/ASMR/Triggers/Tapping.mp3'),
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-bolt',
    variantName: 'Thunder ',
    sound: 'Thunder',
    asset: require('../assets/audio/Background/Thunder_fa-bolt/Thunder .mp3'),
    free: true,
  },
  {
    group: 'Background',
    icon: 'fa-bolt',
    variantName: 'Thunder 2',
    sound: 'Thunder',
    asset: require('../assets/audio/Background/Thunder_fa-bolt/Thunder 2.mp3'),
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-bolt',
    variantName: 'Thunder 3',
    sound: 'Thunder',
    asset: require('../assets/audio/Background/Thunder_fa-bolt/Thunder 3.mp3'),
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-bolt',
    variantName: 'Thunderstorm with rain',
    sound: 'Thunder',
    asset: require('../assets/audio/Background/Thunder_fa-bolt/Thunderstorm with rain.mp3'),
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-train',
    variantName: 'Train',
    sound: 'Train',
    asset: require('../assets/audio/Locations/Train_fa-train/Train.mp3'),
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-city',
    variantName: 'Transport movement',
    sound: 'Street, city',
    asset: require('../assets/audio/Locations/Street, city_fa-city/Transport movement.mp3'),
    free: false,
  },
  {
    group: 'Tweak',
    icon: 'fa-keyboard',
    variantName: 'Typewriter',
    sound: 'Keyboard',
    asset: require('../assets/audio/Tweak/Keyboard_fa-keyboard/Typewriter.mp3'),
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-mountains',
    variantName: 'Underground waterfall',
    sound: 'Waterfall',
    asset: require('../assets/audio/Background/Waterfall_fa-mountains/Underground waterfall.mp3'),
    free: true,
  },
  {
    group: 'Tweak',
    icon: 'fa-vacuum',
    variantName: 'Vacuum cleaner',
    sound: 'Vacuum cleaner',
    asset: require('../assets/audio/Tweak/Vacuum cleaner_fa-vacuum/Vacuum cleaner.mp3'),
    free: true,
  },
  {
    group: 'Tweak',
    icon: 'fa-vacuum',
    variantName: 'Vacuum cleaner 2',
    sound: 'Vacuum cleaner',
    asset: require('../assets/audio/Tweak/Vacuum cleaner_fa-vacuum/Vacuum cleaner 2.mp3'),
    free: false,
  },
  {
    group: 'ASMR',
    variantName: 'Velcro',
    sound: 'Triggers',
    asset: require('../assets/audio/ASMR/Triggers/Velcro.mp3'),
    free: false,
  },
  {
    group: 'Tweak',
    icon: 'fa-clock',
    variantName: 'Wall Clock',
    sound: 'Clocks',
    asset: require('../assets/audio/Tweak/Clocks_fa-clock/Wall Clock.mp3'),
    free: false,
  },
  {
    group: 'Tweak',
    icon: 'fa-clock',
    variantName: 'Wall Clock 2',
    sound: 'Clocks',
    asset: require('../assets/audio/Tweak/Clocks_fa-clock/Wall Clock 2.mp3'),
    free: false,
  },
  {
    group: 'Tweak',
    icon: 'fa-clock',
    variantName: 'Wall Clock 3',
    sound: 'Clocks',
    asset: require('../assets/audio/Tweak/Clocks_fa-clock/Wall Clock 3.mp3'),
    free: false,
  },
  {
    group: 'Tweak',
    icon: 'fa-clock',
    variantName: 'Wall clock 4',
    sound: 'Clocks',
    asset: require('../assets/audio/Tweak/Clocks_fa-clock/Wall clock 4.mp3'),
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-mountains',
    variantName: 'Waterfall',
    sound: 'Waterfall',
    asset: require('../assets/audio/Background/Waterfall_fa-mountains/Waterfall.mp3'),
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-mountains',
    variantName: 'Waterfall 2',
    sound: 'Waterfall',
    asset: require('../assets/audio/Background/Waterfall_fa-mountains/Waterfall 2.mp3'),
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-whale',
    variantName: 'Whale ',
    sound: 'Whale',
    asset: require('../assets/audio/Others/Whale_fa-whale/Whale .mp3'),
    free: true,
  },
  {
    group: 'Others',
    icon: 'fa-whale',
    variantName: 'Whale (Scary sound)',
    sound: 'Whale',
    asset: require('../assets/audio/Others/Whale_fa-whale/Whale (Scary sound).mp3'),
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-whale',
    variantName: 'Whale 2',
    sound: 'Whale',
    asset: require('../assets/audio/Others/Whale_fa-whale/Whale 2.mp3'),
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-whale',
    variantName: 'Whale 3',
    sound: 'Whale',
    asset: require('../assets/audio/Others/Whale_fa-whale/Whale 3.mp3'),
    free: false,
  },
  {
    group: 'ASMR',
    variantName: 'Whiser 2',
    sound: 'Whisper',
    asset: require('../assets/audio/ASMR/Whisper/Whiser 2.mp3'),
    free: false,
  },
  {
    group: 'ASMR',
    variantName: 'Whisper',
    sound: 'Whisper',
    asset: require('../assets/audio/ASMR/Whisper/Whisper.mp3'),
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-wind',
    variantName: 'Whistling',
    sound: 'Wind',
    asset: require('../assets/audio/Background/Wind_fa-wind/Whistling.mp3'),
    free: false,
  },
  {
    group: 'Color noise',
    icon: 'fa-tv',
    variantName: 'White noise',
    sound: 'White noise',
    asset: require('../assets/audio/Color noise/White noise_fa-tv/White noise.mp3'),
    free: true,
  },
  {
    group: 'Tweak',
    icon: 'fa-music',
    variantName: 'Wind chimes',
    sound: 'Wind chimes',
    asset: require('../assets/audio/Tweak/Wind chimes_fa-music/Wind chimes.mp3'),
    free: true,
  },
  {
    group: 'Tweak',
    icon: 'fa-music',
    variantName: 'Wind chimes 2',
    sound: 'Wind chimes',
    asset: require('../assets/audio/Tweak/Wind chimes_fa-music/Wind chimes 2.mp3'),
    free: false,
  },
  {
    group: 'Tweak',
    icon: 'fa-music',
    variantName: 'Wind chimes 3',
    sound: 'Wind chimes',
    asset: require('../assets/audio/Tweak/Wind chimes_fa-music/Wind chimes 3.mp3'),
    free: false,
  },
  {
    group: 'Tweak',
    icon: 'fa-music',
    variantName: 'Wind chimes 4',
    sound: 'Wind chimes',
    asset: require('../assets/audio/Tweak/Wind chimes_fa-music/Wind chimes 4.mp3'),
    free: false,
  },
  {
    group: 'ASMR',
    icon: 'fa-hands-clapping',
    variantName: 'Wood',
    sound: 'Tapping',
    asset: require('../assets/audio/ASMR/Tapping_fa-hands-clapping/Wood.mp3'),
    free: false,
  },
  {
    group: 'ASMR',
    variantName: 'Wood',
    sound: 'Triggers',
    asset: require('../assets/audio/ASMR/Triggers/Wood.mp3'),
    free: false,
  },
  {
    group: 'ASMR',
    variantName: 'Wood 2',
    sound: 'Triggers',
    asset: require('../assets/audio/ASMR/Triggers/Wood 2.mp3'),
    free: false,
  },
  {
    group: 'ASMR',
    variantName: 'Wood 3',
    sound: 'Triggers',
    asset: require('../assets/audio/ASMR/Triggers/Wood 3.mp3'),
    free: false,
  },
  {
    group: 'ASMR',
    variantName: 'Wood 4',
    sound: 'Triggers',
    asset: require('../assets/audio/ASMR/Triggers/Wood 4.mp3'),
    free: false,
  },
  {
    group: 'ASMR',
    icon: 'fa-hands-clapping',
    variantName: 'Wood(1)',
    sound: 'Tapping',
    asset: require('../assets/audio/ASMR/Tapping_fa-hands-clapping/Wood(1).mp3'),
    free: false,
  },
  {
    group: 'ASMR',
    variantName: 'Wool',
    sound: 'Triggers',
    asset: require('../assets/audio/ASMR/Triggers/Wool.mp3'),
    free: false,
  },
  {
    group: 'Tweak',
    icon: 'fa-clock',
    variantName: 'Wrist watch',
    sound: 'Clocks',
    asset: require('../assets/audio/Tweak/Clocks_fa-clock/Wrist watch.mp3'),
    free: false,
  },
  {
    group: 'Tweak',
    icon: 'fa-clock',
    variantName: 'Wrist watch 2',
    sound: 'Clocks',
    asset: require('../assets/audio/Tweak/Clocks_fa-clock/Wrist watch 2.mp3'),
    free: false,
  },
  {
    group: 'ASMR',
    variantName: 'Writing pencil',
    sound: 'Triggers',
    asset: require('../assets/audio/ASMR/Triggers/Writing pencil.mp3'),
    free: false,
  },
  {
    group: 'ASMR',
    variantName: 'plastic bag',
    sound: 'Triggers',
    asset: require('../assets/audio/ASMR/Triggers/plastic bag.mp3'),
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-cloud-showers-heavy',
    variantName: 'rain on the window',
    sound: 'Rain',
    asset: require('../assets/audio/Background/Rain_fa-cloud-showers-heavy/rain on the window.mp3'),
    free: false,
  },
];
export default sounds as ISoundItem[];
