export interface ISoundItem {
  group: string;
  icon?: string;
  path: string;
  sound: string;
  variantName: string;
  free: boolean;
}
const sounds = [
  {
    group: 'Locations',
    icon: 'fa-basketball',
    path: '../assets/Locations/Basketball court_fa-basketball/Basketball game_320.m4a',
    variantName: 'Basketball game',
    sound: 'Basketball court',
    free: true,
  },
  {
    group: 'Locations',
    icon: 'fa-basketball',
    path: '../assets/Locations/Basketball court_fa-basketball/Basketball game 2_320.m4a',
    variantName: 'Basketball game 2',
    sound: 'Basketball court',
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-basketball',
    path: '../assets/Locations/Basketball court_fa-basketball/Basketball training_320.m4a',
    variantName: 'Basketball training',
    sound: 'Basketball court',
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-water',
    path: '../assets/Background/Waves_fa-water/Beach_320.m4a',
    variantName: 'Beach',
    sound: 'Waves',
    free: true,
  },
  {
    group: 'Background',
    icon: 'fa-water',
    path: '../assets/Background/Waves_fa-water/Beach 2_320.m4a',
    variantName: 'Beach 2',
    sound: 'Waves',
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-water',
    path: '../assets/Background/Waves_fa-water/Beach 3_320.m4a',
    variantName: 'Beach 3',
    sound: 'Waves',
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-dove',
    path: '../assets/Background/Birdsong_fa-dove/Birdsong 1_320.m4a',
    variantName: 'Birdsong 1',
    sound: 'Birdsong',
    free: true,
  },
  {
    group: 'Background',
    icon: 'fa-dove',
    path: '../assets/Background/Birdsong_fa-dove/Birdsong 2_320.m4a',
    variantName: 'Birdsong 2',
    sound: 'Birdsong',
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-dove',
    path: '../assets/Background/Birdsong_fa-dove/Birdsong 3_320.m4a',
    variantName: 'Birdsong 3',
    sound: 'Birdsong',
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-dove',
    path: '../assets/Background/Birdsong_fa-dove/Birdsong 4_320.m4a',
    variantName: 'Birdsong 4',
    sound: 'Birdsong',
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-fire',
    path: '../assets/Background/Bonfire_fa-fire/Bonfire 1_320.m4a',
    variantName: 'Bonfire 1',
    sound: 'Bonfire',
    free: true,
  },
  {
    group: 'Background',
    icon: 'fa-fire',
    path: '../assets/Background/Bonfire_fa-fire/Bonfire 2_320.m4a',
    variantName: 'Bonfire 2',
    sound: 'Bonfire',
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-fire',
    path: '../assets/Background/Bonfire_fa-fire/Bonfire 3_320.m4a',
    variantName: 'Bonfire 3',
    sound: 'Bonfire',
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-fire',
    path: '../assets/Background/Bonfire_fa-fire/Bonfire 4_320.m4a',
    variantName: 'Bonfire 4',
    sound: 'Bonfire',
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-fire',
    path: '../assets/Background/Bonfire_fa-fire/Bonfire 5_320.m4a',
    variantName: 'Bonfire 5',
    sound: 'Bonfire',
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-face-nose-steam',
    path: '../assets/Others/Breath_fa-face-nose-steam/Breathe_320.m4a',
    variantName: 'Breathe',
    sound: 'Breath',
    free: true,
  },
  {
    group: 'Others',
    icon: 'fa-face-nose-steam',
    path: '../assets/Others/Breath_fa-face-nose-steam/Breathe 3_320.m4a',
    variantName: 'Breathe 3',
    sound: 'Breath',
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-face-nose-steam',
    path: '../assets/Others/Breath_fa-face-nose-steam/Breathe(1)_320.m4a',
    variantName: 'Breathe(1)',
    sound: 'Breath',
    free: false,
  },
  {
    group: 'Color noise',
    icon: 'fa-volume',
    path: '../assets/Color noise/Brown noise_fa-volume/Brown Noise_320.m4a',
    variantName: 'Brown Noise',
    sound: 'Brown noise',
    free: true,
  },
  {
    group: 'Tweak',
    icon: 'fa-cauldron',
    path: '../assets/Tweak/Bubbles_fa-cauldron/Bubbles_320.m4a',
    variantName: 'Bubbles',
    sound: 'Bubbles',
    free: true,
  },
  {
    group: 'Tweak',
    icon: 'fa-cauldron',
    path: '../assets/Tweak/Bubbles_fa-cauldron/Bubbles 2_320.m4a',
    variantName: 'Bubbles 2',
    sound: 'Bubbles',
    free: false,
  },
  {
    group: 'Tweak',
    icon: 'fa-cauldron',
    path: '../assets/Tweak/Bubbles_fa-cauldron/Bubbles 3_320.m4a',
    variantName: 'Bubbles 3',
    sound: 'Bubbles',
    free: false,
  },
  {
    group: 'Tweak',
    icon: 'fa-cauldron',
    path: '../assets/Tweak/Bubbles_fa-cauldron/Bubbles 4_320.m4a',
    variantName: 'Bubbles 4',
    sound: 'Bubbles',
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-plane',
    path: '../assets/Locations/Plane_fa-plane/Cabin 1_320.m4a',
    variantName: 'Cabin 1',
    sound: 'Plane',
    free: true,
  },
  {
    group: 'Locations',
    icon: 'fa-plane',
    path: '../assets/Locations/Plane_fa-plane/Cabin 2_320.m4a',
    variantName: 'Cabin 2',
    sound: 'Plane',
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-plane',
    path: '../assets/Locations/Plane_fa-plane/Cabin 3_320.m4a',
    variantName: 'Cabin 3',
    sound: 'Plane',
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-mug-saucer',
    path: '../assets/Locations/Cafe_fa-mug-saucer/Cafe (English speech)_320.m4a',
    variantName: 'Cafe (English speech)',
    sound: 'Cafe',
    free: true,
  },
  {
    group: 'Locations',
    icon: 'fa-mug-saucer',
    path: '../assets/Locations/Cafe_fa-mug-saucer/Cafe (Russian speech)_320.m4a',
    variantName: 'Cafe (Russian speech)',
    sound: 'Cafe',
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-mug-saucer',
    path: '../assets/Locations/Cafe_fa-mug-saucer/Cafe 1_320.m4a',
    variantName: 'Cafe 1',
    sound: 'Cafe',
    free: false,
  },
  {
    group: 'ASMR',
    icon: 'fa-hands-clapping',
    path: '../assets/ASMR/Tapping_fa-hands-clapping/Cardboard box_320.m4a',
    variantName: 'Cardboard box',
    sound: 'Tapping',
    free: true,
  },
  {
    group: 'Background',
    icon: 'fa-road',
    path: '../assets/Background/Road_fa-road/Cars, trains_320.m4a',
    variantName: 'Cars, trains',
    sound: 'Road',
    free: true,
  },
  {
    group: 'Locations',
    icon: 'fa-bag-shopping',
    path: '../assets/Locations/Supermarket_fa-bag-shopping/Cash machine_320.m4a',
    variantName: 'Cash machine',
    sound: 'Supermarket',
    free: true,
  },
  {
    group: 'Tweak',
    icon: 'fa-cat',
    path: '../assets/Tweak/Cat purr_fa-cat/Cat purr_320.m4a',
    variantName: 'Cat purr',
    sound: 'Cat purr',
    free: true,
  },
  {
    group: 'Tweak',
    icon: 'fa-cat',
    path: '../assets/Tweak/Cat purr_fa-cat/Cat purr 2_320.m4a',
    variantName: 'Cat purr 2',
    sound: 'Cat purr',
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-bars-staggered',
    path: '../assets/Background/Stream_fa-bars-staggered/Cave stream_320.m4a',
    variantName: 'Cave stream',
    sound: 'Stream',
    free: true,
  },
  {
    group: 'Tweak',
    icon: 'fa-fan',
    path: '../assets/Tweak/Ceiling fan_fa-fan/Ceiling fan_320.m4a',
    variantName: 'Ceiling fan',
    sound: 'Ceiling fan',
    free: true,
  },
  {
    group: 'Tweak',
    icon: 'fa-fan',
    path: '../assets/Tweak/Ceiling fan_fa-fan/Ceiling fan 2_320.m4a',
    variantName: 'Ceiling fan 2',
    sound: 'Ceiling fan',
    free: false,
  },
  {
    group: 'Tweak',
    icon: 'fa-cookie-bite',
    path: '../assets/Tweak/Potato chips_fa-cookie-bite/Chewing_320.m4a',
    variantName: 'Chewing',
    sound: 'Potato chips',
    free: true,
  },
  {
    group: 'Tweak',
    icon: 'fa-cookie-bite',
    path: '../assets/Tweak/Potato chips_fa-cookie-bite/Chewing 2_320.m4a',
    variantName: 'Chewing 2',
    sound: 'Potato chips',
    free: false,
  },
  {
    group: 'Tweak',
    icon: 'fa-cookie-bite',
    path: '../assets/Tweak/Potato chips_fa-cookie-bite/Chewing 3_320.m4a',
    variantName: 'Chewing 3',
    sound: 'Potato chips',
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-feather',
    path: '../assets/Locations/Chicken coop_fa-feather/Chicken coop_320.m4a',
    variantName: 'Chicken coop',
    sound: 'Chicken coop',
    free: true,
  },
  {
    group: 'Locations',
    icon: 'fa-feather',
    path: '../assets/Locations/Chicken coop_fa-feather/Chicken coop 1_320.m4a',
    variantName: 'Chicken coop 1',
    sound: 'Chicken coop',
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-feather',
    path: '../assets/Locations/Chicken coop_fa-feather/Chickens_320.m4a',
    variantName: 'Chickens',
    sound: 'Chicken coop',
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-bell',
    path: '../assets/Locations/Bells_fa-bell/Chime_320.m4a',
    variantName: 'Chime',
    sound: 'Bells',
    free: true,
  },
  {
    group: 'Locations',
    icon: 'fa-bell',
    path: '../assets/Locations/Bells_fa-bell/Chime 2_320.m4a',
    variantName: 'Chime 2',
    sound: 'Bells',
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-bell',
    path: '../assets/Locations/Bells_fa-bell/Chime 3_320.m4a',
    variantName: 'Chime 3',
    sound: 'Bells',
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-bell',
    path: '../assets/Locations/Bells_fa-bell/Chime 4_320.m4a',
    variantName: 'Chime 4',
    sound: 'Bells',
    free: false,
  },
  {
    group: 'Tweak',
    icon: 'fa-clock',
    path: '../assets/Tweak/Clocks_fa-clock/Chimes_320.m4a',
    variantName: 'Chimes',
    sound: 'Clocks',
    free: true,
  },
  {
    group: 'Tweak',
    icon: 'fa-clock',
    path: '../assets/Tweak/Clocks_fa-clock/Clock tower_320.m4a',
    variantName: 'Clock tower',
    sound: 'Clocks',
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-water',
    path: '../assets/Background/Waves_fa-water/Coastal cave_320.m4a',
    variantName: 'Coastal cave',
    sound: 'Waves',
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-mug-saucer',
    path: '../assets/Locations/Cafe_fa-mug-saucer/Coffee machine_320.m4a',
    variantName: 'Coffee machine',
    sound: 'Cafe',
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-house',
    path: '../assets/Background/Country life_fa-house/Country life_320.m4a',
    variantName: 'Country life',
    sound: 'Country life',
    free: true,
  },
  {
    group: 'Background',
    icon: 'fa-house',
    path: '../assets/Background/Country life_fa-house/Country life 2_320.m4a',
    variantName: 'Country life 2',
    sound: 'Country life',
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-house',
    path: '../assets/Background/Country life_fa-house/Country life 3_320.m4a',
    variantName: 'Country life 3',
    sound: 'Country life',
    free: false,
  },
  {
    group: 'Tweak',
    icon: 'fa-octopus-deploy',
    path: '../assets/Tweak/Deep sea_fa-octopus-deploy/Depth_320.m4a',
    variantName: 'Depth',
    sound: 'Deep sea',
    free: true,
  },
  {
    group: 'Tweak',
    icon: 'fa-octopus-deploy',
    path: '../assets/Tweak/Deep sea_fa-octopus-deploy/Depth 2_320.m4a',
    variantName: 'Depth 2',
    sound: 'Deep sea',
    free: false,
  },
  {
    group: 'Tweak',
    icon: 'fa-octopus-deploy',
    path: '../assets/Tweak/Deep sea_fa-octopus-deploy/Depth 3_320.m4a',
    variantName: 'Depth 3',
    sound: 'Deep sea',
    free: false,
  },
  {
    group: 'Tweak',
    icon: 'fa-octopus-deploy',
    path: '../assets/Tweak/Deep sea_fa-octopus-deploy/Depth 4_320.m4a',
    variantName: 'Depth 4',
    sound: 'Deep sea',
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-wind',
    path: '../assets/Background/Wind_fa-wind/Desert_320.m4a',
    variantName: 'Desert',
    sound: 'Wind',
    free: true,
  },
  {
    group: 'ASMR',
    path: '../assets/ASMR/Triggers/Ear massage_320.m4a',
    variantName: 'Ear massage',
    sound: 'Triggers',
    free: true,
  },
  {
    group: 'Others',
    icon: 'fa-engine',
    path: '../assets/Others/Engine_fa-engine/Engine_320.m4a',
    variantName: 'Engine',
    sound: 'Engine',
    free: true,
  },
  {
    group: 'Others',
    icon: 'fa-engine',
    path: '../assets/Others/Engine_fa-engine/Engine 2_320.m4a',
    variantName: 'Engine 2',
    sound: 'Engine',
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-engine',
    path: '../assets/Others/Engine_fa-engine/Engine 3_320.m4a',
    variantName: 'Engine 3',
    sound: 'Engine',
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-engine',
    path: '../assets/Others/Engine_fa-engine/Engine 4_320.m4a',
    variantName: 'Engine 4',
    sound: 'Engine',
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-church',
    path: '../assets/Locations/Chants_fa-church/English chants_320.m4a',
    variantName: 'English chants',
    sound: 'Chants',
    free: true,
  },
  {
    group: 'Locations',
    icon: 'fa-church',
    path: '../assets/Locations/Chants_fa-church/English chants to organ_320.m4a',
    variantName: 'English chants to organ',
    sound: 'Chants',
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-train-subway',
    path: '../assets/Locations/Underground_fa-train-subway/Escalator_320.m4a',
    variantName: 'Escalator',
    sound: 'Underground',
    free: true,
  },
  {
    group: 'ASMR',
    icon: 'fa-scissors',
    path: '../assets/ASMR/Barbershop_fa-scissors/Face cleaning_320.m4a',
    variantName: 'Face cleaning',
    sound: 'Barbershop',
    free: true,
  },
  {
    group: 'Background',
    icon: 'fa-wind',
    path: '../assets/Background/Wind_fa-wind/Far_320.m4a',
    variantName: 'Far',
    sound: 'Wind',
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-tractor',
    path: '../assets/Locations/Farm_fa-tractor/Farm_320.m4a',
    variantName: 'Farm',
    sound: 'Farm',
    free: true,
  },
  {
    group: 'Locations',
    icon: 'fa-tractor',
    path: '../assets/Locations/Farm_fa-tractor/Farm 2_320.m4a',
    variantName: 'Farm 2',
    sound: 'Farm',
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-tractor',
    path: '../assets/Locations/Farm_fa-tractor/Farm 3_320.m4a',
    variantName: 'Farm 3',
    sound: 'Farm',
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-tractor',
    path: '../assets/Locations/Farm_fa-tractor/Farm 4_320.m4a',
    variantName: 'Farm 4',
    sound: 'Farm',
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-comments',
    path: '../assets/Locations/Conversations_fa-comments/Female conversation (English speech)_320.m4a',
    variantName: 'Female conversation (English speech)',
    sound: 'Conversations',
    free: true,
  },
  {
    group: 'Background',
    icon: 'fa-fire',
    path: '../assets/Background/Bonfire_fa-fire/Fireplace_320.m4a',
    variantName: 'Fireplace',
    sound: 'Bonfire',
    free: false,
  },
  {
    group: 'Tweak',
    path: '../assets/Tweak/Fireworks/Fireworks _320.m4a',
    variantName: 'Fireworks ',
    sound: 'Fireworks',
    free: true,
  },
  {
    group: 'Tweak',
    path: '../assets/Tweak/Fireworks/Fireworks 2_320.m4a',
    variantName: 'Fireworks 2',
    sound: 'Fireworks',
    free: false,
  },
  {
    group: 'Tweak',
    path: '../assets/Tweak/Fireworks/Fireworks 3_320.m4a',
    variantName: 'Fireworks 3',
    sound: 'Fireworks',
    free: false,
  },
  {
    group: 'ASMR',
    path: '../assets/ASMR/Triggers/Fizzy_320.m4a',
    variantName: 'Fizzy',
    sound: 'Triggers',
    free: false,
  },
  {
    group: 'ASMR',
    path: '../assets/ASMR/Triggers/Foam_320.m4a',
    variantName: 'Foam',
    sound: 'Triggers',
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-tree',
    path: '../assets/Background/Forest_fa-tree/Forest 1_320.m4a',
    variantName: 'Forest 1',
    sound: 'Forest',
    free: true,
  },
  {
    group: 'Background',
    icon: 'fa-tree',
    path: '../assets/Background/Forest_fa-tree/Forest 2_320.m4a',
    variantName: 'Forest 2',
    sound: 'Forest',
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-tree',
    path: '../assets/Background/Forest_fa-tree/Forest 3_320.m4a',
    variantName: 'Forest 3',
    sound: 'Forest',
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-tree',
    path: '../assets/Background/Forest_fa-tree/Forest 4_320.m4a',
    variantName: 'Forest 4',
    sound: 'Forest',
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-tree',
    path: '../assets/Background/Forest_fa-tree/Forest 5_320.m4a',
    variantName: 'Forest 5',
    sound: 'Forest',
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-comments',
    path: '../assets/Locations/Conversations_fa-comments/French speech_320.m4a',
    variantName: 'French speech',
    sound: 'Conversations',
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-frog',
    path: '../assets/Background/Frog_fa-frog/Frogs and cicadas_320.m4a',
    variantName: 'Frogs and cicadas',
    sound: 'Frog',
    free: true,
  },
  {
    group: 'Background',
    icon: 'fa-frog',
    path: '../assets/Background/Frog_fa-frog/Frogs and cicadas 2_320.m4a',
    variantName: 'Frogs and cicadas 2',
    sound: 'Frog',
    free: false,
  },
  {
    group: 'Tweak',
    icon: 'fa-user-hair',
    path: '../assets/Tweak/Hair dryer_fa-user-hair/Hair dryer_320.m4a',
    variantName: 'Hair dryer',
    sound: 'Hair dryer',
    free: true,
  },
  {
    group: 'Tweak',
    icon: 'fa-user-hair',
    path: '../assets/Tweak/Hair dryer_fa-user-hair/Hair dryer 2_320.m4a',
    variantName: 'Hair dryer 2',
    sound: 'Hair dryer',
    free: false,
  },
  {
    group: 'Tweak',
    icon: 'fa-user-hair',
    path: '../assets/Tweak/Hair dryer_fa-user-hair/Hair dryer 3_320.m4a',
    variantName: 'Hair dryer 3',
    sound: 'Hair dryer',
    free: false,
  },
  {
    group: 'ASMR',
    icon: 'fa-scissors',
    path: '../assets/ASMR/Barbershop_fa-scissors/Haircut_320.m4a',
    variantName: 'Haircut',
    sound: 'Barbershop',
    free: false,
  },
  {
    group: 'ASMR',
    icon: 'fa-scissors',
    path: '../assets/ASMR/Barbershop_fa-scissors/Haircut 2_320.m4a',
    variantName: 'Haircut 2',
    sound: 'Barbershop',
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-wind',
    path: '../assets/Background/Wind_fa-wind/Howling_320.m4a',
    variantName: 'Howling',
    sound: 'Wind',
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-plane',
    path: '../assets/Locations/Plane_fa-plane/In the plane_320.m4a',
    variantName: 'In the plane',
    sound: 'Plane',
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-plane',
    path: '../assets/Locations/Plane_fa-plane/In the plane 2_320.m4a',
    variantName: 'In the plane 2',
    sound: 'Plane',
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-train',
    path: '../assets/Locations/Train_fa-train/Inside the train_320.m4a',
    variantName: 'Inside the train',
    sound: 'Train',
    free: true,
  },
  {
    group: 'Locations',
    icon: 'fa-train',
    path: '../assets/Locations/Train_fa-train/Inside the train 2_320.m4a',
    variantName: 'Inside the train 2',
    sound: 'Train',
    free: false,
  },
  {
    group: 'Tweak',
    icon: 'fa-print',
    path: '../assets/Tweak/Printer_fa-print/Jet printer_320.m4a',
    variantName: 'Jet printer',
    sound: 'Printer',
    free: true,
  },
  {
    group: 'Tweak',
    icon: 'fa-print',
    path: '../assets/Tweak/Printer_fa-print/Jet printer 2_320.m4a',
    variantName: 'Jet printer 2',
    sound: 'Printer',
    free: false,
  },
  {
    group: 'Tweak',
    icon: 'fa-keyboard',
    path: '../assets/Tweak/Keyboard_fa-keyboard/Keyboard_320.m4a',
    variantName: 'Keyboard',
    sound: 'Keyboard',
    free: true,
  },
  {
    group: 'Tweak',
    icon: 'fa-keyboard',
    path: '../assets/Tweak/Keyboard_fa-keyboard/Keyboard 2_320.m4a',
    variantName: 'Keyboard 2',
    sound: 'Keyboard',
    free: false,
  },
  {
    group: 'ASMR',
    icon: 'fa-hands-clapping',
    path: '../assets/ASMR/Tapping_fa-hands-clapping/Leater cover_320.m4a',
    variantName: 'Leater cover',
    sound: 'Tapping',
    free: false,
  },
  {
    group: 'ASMR',
    icon: 'fa-hands-clapping',
    path: '../assets/ASMR/Tapping_fa-hands-clapping/Leather pillow_320.m4a',
    variantName: 'Leather pillow',
    sound: 'Tapping',
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-wind',
    path: '../assets/Background/Wind_fa-wind/Light_320.m4a',
    variantName: 'Light',
    sound: 'Wind',
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-volcano',
    path: '../assets/Others/Magma_fa-volcano/Magma_320.m4a',
    variantName: 'Magma',
    sound: 'Magma',
    free: true,
  },
  {
    group: 'Others',
    icon: 'fa-volcano',
    path: '../assets/Others/Magma_fa-volcano/Magma 2_320.m4a',
    variantName: 'Magma 2',
    sound: 'Magma',
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-volcano',
    path: '../assets/Others/Magma_fa-volcano/Magma 3_320.m4a',
    variantName: 'Magma 3',
    sound: 'Magma',
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-comments',
    path: '../assets/Locations/Conversations_fa-comments/Man at the bar (English speech_320.m4a',
    variantName: 'Man at the bar (English speech',
    sound: 'Conversations',
    free: false,
  },
  {
    group: 'Tweak',
    icon: 'fa-print',
    path: '../assets/Tweak/Printer_fa-print/Matrix printer_320.m4a',
    variantName: 'Matrix printer',
    sound: 'Printer',
    free: false,
  },
  {
    group: 'Tweak',
    icon: 'fa-print',
    path: '../assets/Tweak/Printer_fa-print/Matrix printer 2_320.m4a',
    variantName: 'Matrix printer 2',
    sound: 'Printer',
    free: false,
  },
  {
    group: 'Tweak',
    icon: 'fa-clock',
    path: '../assets/Tweak/Clocks_fa-clock/Mechanic timer_320.m4a',
    variantName: 'Mechanic timer',
    sound: 'Clocks',
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-wind',
    path: '../assets/Background/Wind_fa-wind/Medium_320.m4a',
    variantName: 'Medium',
    sound: 'Wind',
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-wind',
    path: '../assets/Background/Wind_fa-wind/Medium 2_320.m4a',
    variantName: 'Medium 2',
    sound: 'Wind',
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-comments',
    path: '../assets/Locations/Conversations_fa-comments/Men at the bar (German speech)_320.m4a',
    variantName: 'Men at the bar (German speech)',
    sound: 'Conversations',
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-bars-staggered',
    path: '../assets/Background/Stream_fa-bars-staggered/Mountain creek_320.m4a',
    variantName: 'Mountain creek',
    sound: 'Stream',
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-comments',
    path: '../assets/Locations/Conversations_fa-comments/Neighbors (English speech)_320.m4a',
    variantName: 'Neighbors (English speech)',
    sound: 'Conversations',
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-train-subway',
    path: '../assets/Locations/Underground_fa-train-subway/New york subway_320.m4a',
    variantName: 'New york subway',
    sound: 'Underground',
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-moon',
    path: '../assets/Background/Night_fa-moon/Night_320.m4a',
    variantName: 'Night',
    sound: 'Night',
    free: true,
  },
  {
    group: 'Background',
    icon: 'fa-moon',
    path: '../assets/Background/Night_fa-moon/Night 2_320.m4a',
    variantName: 'Night 2',
    sound: 'Night',
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-moon',
    path: '../assets/Background/Night_fa-moon/Night in city_320.m4a',
    variantName: 'Night in city',
    sound: 'Night',
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-moon',
    path: '../assets/Background/Night_fa-moon/Night in city 2_320.m4a',
    variantName: 'Night in city 2',
    sound: 'Night',
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-comments',
    path: '../assets/Locations/Conversations_fa-comments/Night talk_320.m4a',
    variantName: 'Night talk',
    sound: 'Conversations',
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-bag-shopping',
    path: '../assets/Locations/Supermarket_fa-bag-shopping/Old cash machine_320.m4a',
    variantName: 'Old cash machine',
    sound: 'Supermarket',
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-wind',
    path: '../assets/Background/Wind_fa-wind/Ominous_320.m4a',
    variantName: 'Ominous',
    sound: 'Wind',
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-person-walking',
    path: '../assets/Others/Walk_fa-person-walking/On earth_320.m4a',
    variantName: 'On earth',
    sound: 'Walk',
    free: true,
  },
  {
    group: 'Others',
    icon: 'fa-person-walking',
    path: '../assets/Others/Walk_fa-person-walking/On earth 2_320.m4a',
    variantName: 'On earth 2',
    sound: 'Walk',
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-person-walking',
    path: '../assets/Others/Walk_fa-person-walking/On earth 3_320.m4a',
    variantName: 'On earth 3',
    sound: 'Walk',
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-person-walking',
    path: '../assets/Others/Walk_fa-person-walking/On earth 4_320.m4a',
    variantName: 'On earth 4',
    sound: 'Walk',
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-person-walking',
    path: '../assets/Others/Walk_fa-person-walking/On grass_320.m4a',
    variantName: 'On grass',
    sound: 'Walk',
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-person-walking',
    path: '../assets/Others/Walk_fa-person-walking/On grass 2_320.m4a',
    variantName: 'On grass 2',
    sound: 'Walk',
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-person-walking',
    path: '../assets/Others/Walk_fa-person-walking/On grass 3_320.m4a',
    variantName: 'On grass 3',
    sound: 'Walk',
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-person-walking',
    path: '../assets/Others/Walk_fa-person-walking/On leaves_320.m4a',
    variantName: 'On leaves',
    sound: 'Walk',
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-person-walking',
    path: '../assets/Others/Walk_fa-person-walking/On leaves 2_320.m4a',
    variantName: 'On leaves 2',
    sound: 'Walk',
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-person-walking',
    path: '../assets/Others/Walk_fa-person-walking/On leaves 3_320.m4a',
    variantName: 'On leaves 3',
    sound: 'Walk',
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-person-walking',
    path: '../assets/Others/Walk_fa-person-walking/On sand_320.m4a',
    variantName: 'On sand',
    sound: 'Walk',
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-person-walking',
    path: '../assets/Others/Walk_fa-person-walking/On sand 2_320.m4a',
    variantName: 'On sand 2',
    sound: 'Walk',
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-person-walking',
    path: '../assets/Others/Walk_fa-person-walking/On sand 3_320.m4a',
    variantName: 'On sand 3',
    sound: 'Walk',
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-person-walking',
    path: '../assets/Others/Walk_fa-person-walking/On snow_320.m4a',
    variantName: 'On snow',
    sound: 'Walk',
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-person-walking',
    path: '../assets/Others/Walk_fa-person-walking/On snow 2_320.m4a',
    variantName: 'On snow 2',
    sound: 'Walk',
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-person-walking',
    path: '../assets/Others/Walk_fa-person-walking/On snow 3_320.m4a',
    variantName: 'On snow 3',
    sound: 'Walk',
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-person-walking',
    path: '../assets/Others/Walk_fa-person-walking/On snow 4_320.m4a',
    variantName: 'On snow 4',
    sound: 'Walk',
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-person-walking',
    path: '../assets/Others/Walk_fa-person-walking/On snow 5_320.m4a',
    variantName: 'On snow 5',
    sound: 'Walk',
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-person-walking',
    path: '../assets/Others/Walk_fa-person-walking/On snow 6_320.m4a',
    variantName: 'On snow 6',
    sound: 'Walk',
    free: false,
  },
  {
    group: 'Color noise',
    icon: 'fa-waveform',
    path: '../assets/Color noise/Pink noise_fa-waveform/Pink noise_320.m4a',
    variantName: 'Pink noise',
    sound: 'Pink noise',
    free: true,
  },
  {
    group: 'Locations',
    icon: 'fa-plane',
    path: '../assets/Locations/Plane_fa-plane/Plane_320.m4a',
    variantName: 'Plane',
    sound: 'Plane',
    free: false,
  },
  {
    group: 'ASMR',
    icon: 'fa-hands-clapping',
    path: '../assets/ASMR/Tapping_fa-hands-clapping/Plastic_320.m4a',
    variantName: 'Plastic',
    sound: 'Tapping',
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-puzzle-piece',
    path: '../assets/Locations/Playground_fa-puzzle-piece/Playground_320.m4a',
    variantName: 'Playground',
    sound: 'Playground',
    free: true,
  },
  {
    group: 'Locations',
    icon: 'fa-puzzle-piece',
    path: '../assets/Locations/Playground_fa-puzzle-piece/Playground 2_320.m4a',
    variantName: 'Playground 2',
    sound: 'Playground',
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-puzzle-piece',
    path: '../assets/Locations/Playground_fa-puzzle-piece/Playground 3_320.m4a',
    variantName: 'Playground 3',
    sound: 'Playground',
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-puzzle-piece',
    path: '../assets/Locations/Playground_fa-puzzle-piece/Playground 4_320.m4a',
    variantName: 'Playground 4',
    sound: 'Playground',
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-sailboat',
    path: '../assets/Others/Boat_fa-sailboat/Powerboat_320.m4a',
    variantName: 'Powerboat',
    sound: 'Boat',
    free: true,
  },
  {
    group: 'Others',
    icon: 'fa-sailboat',
    path: '../assets/Others/Boat_fa-sailboat/Powerboat 2_320.m4a',
    variantName: 'Powerboat 2',
    sound: 'Boat',
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-mosque',
    path: '../assets/Locations/Mosque_fa-mosque/Prayer_320.m4a',
    variantName: 'Prayer',
    sound: 'Mosque',
    free: true,
  },
  {
    group: 'Locations',
    icon: 'fa-train',
    path: '../assets/Locations/Train_fa-train/Railway station_320.m4a',
    variantName: 'Railway station',
    sound: 'Train',
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-cloud-showers-heavy',
    path: '../assets/Background/Rain_fa-cloud-showers-heavy/Rain_320.m4a',
    variantName: 'Rain',
    sound: 'Rain',
    free: true,
  },
  {
    group: 'Background',
    icon: 'fa-cloud-showers-heavy',
    path: '../assets/Background/Rain_fa-cloud-showers-heavy/Rain 2_320.m4a',
    variantName: 'Rain 2',
    sound: 'Rain',
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-cloud-showers-heavy',
    path: '../assets/Background/Rain_fa-cloud-showers-heavy/Rain 3_320.m4a',
    variantName: 'Rain 3',
    sound: 'Rain',
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-cloud-showers-heavy',
    path: '../assets/Background/Rain_fa-cloud-showers-heavy/Rain on the tent_320.m4a',
    variantName: 'Rain on the tent',
    sound: 'Rain',
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-cloud-showers-heavy',
    path: '../assets/Background/Rain_fa-cloud-showers-heavy/Rain over un umbrella_320.m4a',
    variantName: 'Rain over un umbrella',
    sound: 'Rain',
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-cloud-showers-heavy',
    path: '../assets/Background/Rain_fa-cloud-showers-heavy/Rain with thunderstorm_320.m4a',
    variantName: 'Rain with thunderstorm',
    sound: 'Rain',
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-road',
    path: '../assets/Background/Road_fa-road/Road_320.m4a',
    variantName: 'Road',
    sound: 'Road',
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-road',
    path: '../assets/Background/Road_fa-road/Road 2_320.m4a',
    variantName: 'Road 2',
    sound: 'Road',
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-water',
    path: '../assets/Background/Waves_fa-water/Rocky coast_320.m4a',
    variantName: 'Rocky coast',
    sound: 'Waves',
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-sailboat',
    path: '../assets/Others/Boat_fa-sailboat/Rowing boat_320.m4a',
    variantName: 'Rowing boat',
    sound: 'Boat',
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-sailboat',
    path: '../assets/Others/Boat_fa-sailboat/Rowing boat 2_320.m4a',
    variantName: 'Rowing boat 2',
    sound: 'Boat',
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-church',
    path: '../assets/Locations/Chants_fa-church/Russian chants_320.m4a',
    variantName: 'Russian chants',
    sound: 'Chants',
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-fire',
    path: '../assets/Background/Bonfire_fa-fire/Smouldering coals_320.m4a',
    variantName: 'Smouldering coals',
    sound: 'Bonfire',
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-face-nose-steam',
    path: '../assets/Others/Breath_fa-face-nose-steam/Sniff_320.m4a',
    variantName: 'Sniff',
    sound: 'Breath',
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-face-nose-steam',
    path: '../assets/Others/Breath_fa-face-nose-steam/Sniff 2_320.m4a',
    variantName: 'Sniff 2',
    sound: 'Breath',
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-face-nose-steam',
    path: '../assets/Others/Breath_fa-face-nose-steam/Snore_320.m4a',
    variantName: 'Snore',
    sound: 'Breath',
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-road',
    path: '../assets/Background/Road_fa-road/Snowy road_320.m4a',
    variantName: 'Snowy road',
    sound: 'Road',
    free: false,
  },
  {
    group: 'Tweak',
    icon: 'fa-user-astronaut',
    path: '../assets/Tweak/Space_fa-user-astronaut/Space_320.m4a',
    variantName: 'Space',
    sound: 'Space',
    free: true,
  },
  {
    group: 'Tweak',
    icon: 'fa-user-astronaut',
    path: '../assets/Tweak/Space_fa-user-astronaut/Space 2_320.m4a',
    variantName: 'Space 2',
    sound: 'Space',
    free: false,
  },
  {
    group: 'Tweak',
    icon: 'fa-user-astronaut',
    path: '../assets/Tweak/Space_fa-user-astronaut/Space 3_320.m4a',
    variantName: 'Space 3',
    sound: 'Space',
    free: false,
  },
  {
    group: 'Tweak',
    icon: 'fa-user-astronaut',
    path: '../assets/Tweak/Space_fa-user-astronaut/Space 4_320.m4a',
    variantName: 'Space 4',
    sound: 'Space',
    free: false,
  },
  {
    group: 'Tweak',
    icon: 'fa-user-astronaut',
    path: '../assets/Tweak/Space_fa-user-astronaut/Space 5_320.m4a',
    variantName: 'Space 5',
    sound: 'Space',
    free: false,
  },
  {
    group: 'ASMR',
    path: '../assets/ASMR/Triggers/Sponge_320.m4a',
    variantName: 'Sponge',
    sound: 'Triggers',
    free: false,
  },
  {
    group: 'ASMR',
    icon: 'fa-scissors',
    path: '../assets/ASMR/Barbershop_fa-scissors/Spraying_320.m4a',
    variantName: 'Spraying',
    sound: 'Barbershop',
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-train-subway',
    path: '../assets/Locations/Underground_fa-train-subway/St. Petersburg metro_320.m4a',
    variantName: 'St. Petersburg metro',
    sound: 'Underground',
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-person-walking',
    path: '../assets/Others/Walk_fa-person-walking/Steps_320.m4a',
    variantName: 'Steps',
    sound: 'Walk',
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-person-walking',
    path: '../assets/Others/Walk_fa-person-walking/Steps 2_320.m4a',
    variantName: 'Steps 2',
    sound: 'Walk',
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-person-walking',
    path: '../assets/Others/Walk_fa-person-walking/Steps 3_320.m4a',
    variantName: 'Steps 3',
    sound: 'Walk',
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-person-walking',
    path: '../assets/Others/Walk_fa-person-walking/Steps on the carpet_320.m4a',
    variantName: 'Steps on the carpet',
    sound: 'Walk',
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-person-walking',
    path: '../assets/Others/Walk_fa-person-walking/Steps on the wood_320.m4a',
    variantName: 'Steps on the wood',
    sound: 'Walk',
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-person-walking',
    path: '../assets/Others/Walk_fa-person-walking/Steps on the wood 2_320.m4a',
    variantName: 'Steps on the wood 2',
    sound: 'Walk',
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-water',
    path: '../assets/Background/Waves_fa-water/Storm_320.m4a',
    variantName: 'Storm',
    sound: 'Waves',
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-bars-staggered',
    path: '../assets/Background/Stream_fa-bars-staggered/Stream_320.m4a',
    variantName: 'Stream',
    sound: 'Stream',
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-bars-staggered',
    path: '../assets/Background/Stream_fa-bars-staggered/Stream 2_320.m4a',
    variantName: 'Stream 2',
    sound: 'Stream',
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-bars-staggered',
    path: '../assets/Background/Stream_fa-bars-staggered/Stream 3_320.m4a',
    variantName: 'Stream 3',
    sound: 'Stream',
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-city',
    path: '../assets/Locations/Street, city_fa-city/Street noise_320.m4a',
    variantName: 'Street noise',
    sound: 'Street, city',
    free: true,
  },
  {
    group: 'Locations',
    icon: 'fa-city',
    path: '../assets/Locations/Street, city_fa-city/Street noise 2_320.m4a',
    variantName: 'Street noise 2',
    sound: 'Street, city',
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-wind',
    path: '../assets/Background/Wind_fa-wind/Strong_320.m4a',
    variantName: 'Strong',
    sound: 'Wind',
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-bag-shopping',
    path: '../assets/Locations/Supermarket_fa-bag-shopping/Supermarket_320.m4a',
    variantName: 'Supermarket',
    sound: 'Supermarket',
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-bag-shopping',
    path: '../assets/Locations/Supermarket_fa-bag-shopping/Supermarket(1)_320.m4a',
    variantName: 'Supermarket(1)',
    sound: 'Supermarket',
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-person-swimming',
    path: '../assets/Others/Swim_fa-person-swimming/Swim_320.m4a',
    variantName: 'Swim',
    sound: 'Swim',
    free: true,
  },
  {
    group: 'Others',
    icon: 'fa-person-swimming',
    path: '../assets/Others/Swim_fa-person-swimming/Swim 2_320.m4a',
    variantName: 'Swim 2',
    sound: 'Swim',
    free: false,
  },
  {
    group: 'ASMR',
    path: '../assets/ASMR/Whisper/TCHKTCHKTCHK_320.m4a',
    variantName: 'TCHKTCHKTCHK',
    sound: 'Whisper',
    free: true,
  },
  {
    group: 'ASMR',
    path: '../assets/ASMR/Whisper/TKTKTK_320.m4a',
    variantName: 'TKTKTK',
    sound: 'Whisper',
    free: false,
  },
  {
    group: 'Tweak',
    icon: 'fa-fan-table',
    path: '../assets/Tweak/Table fan_fa-fan-table/Table fan_320.m4a',
    variantName: 'Table fan',
    sound: 'Table fan',
    free: true,
  },
  {
    group: 'Tweak',
    icon: 'fa-fan-table',
    path: '../assets/Tweak/Table fan_fa-fan-table/Table fan 2_320.m4a',
    variantName: 'Table fan 2',
    sound: 'Table fan',
    free: false,
  },
  {
    group: 'ASMR',
    path: '../assets/ASMR/Triggers/Tapping_320.m4a',
    variantName: 'Tapping',
    sound: 'Triggers',
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-bolt',
    path: '../assets/Background/Thunder_fa-bolt/Thunder _320.m4a',
    variantName: 'Thunder ',
    sound: 'Thunder',
    free: true,
  },
  {
    group: 'Background',
    icon: 'fa-bolt',
    path: '../assets/Background/Thunder_fa-bolt/Thunder 2_320.m4a',
    variantName: 'Thunder 2',
    sound: 'Thunder',
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-bolt',
    path: '../assets/Background/Thunder_fa-bolt/Thunder 3_320.m4a',
    variantName: 'Thunder 3',
    sound: 'Thunder',
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-bolt',
    path: '../assets/Background/Thunder_fa-bolt/Thunderstorm with rain_320.m4a',
    variantName: 'Thunderstorm with rain',
    sound: 'Thunder',
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-train',
    path: '../assets/Locations/Train_fa-train/Train_320.m4a',
    variantName: 'Train',
    sound: 'Train',
    free: false,
  },
  {
    group: 'Locations',
    icon: 'fa-city',
    path: '../assets/Locations/Street, city_fa-city/Transport movement_320.m4a',
    variantName: 'Transport movement',
    sound: 'Street, city',
    free: false,
  },
  {
    group: 'Tweak',
    icon: 'fa-keyboard',
    path: '../assets/Tweak/Keyboard_fa-keyboard/Typewriter_320.m4a',
    variantName: 'Typewriter',
    sound: 'Keyboard',
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-mountains',
    path: '../assets/Background/Waterfall_fa-mountains/Underground waterfall_320.m4a',
    variantName: 'Underground waterfall',
    sound: 'Waterfall',
    free: true,
  },
  {
    group: 'Tweak',
    icon: 'fa-vacuum',
    path: '../assets/Tweak/Vacuum cleaner_fa-vacuum/Vacuum cleaner_320.m4a',
    variantName: 'Vacuum cleaner',
    sound: 'Vacuum cleaner',
    free: true,
  },
  {
    group: 'Tweak',
    icon: 'fa-vacuum',
    path: '../assets/Tweak/Vacuum cleaner_fa-vacuum/Vacuum cleaner 2_320.m4a',
    variantName: 'Vacuum cleaner 2',
    sound: 'Vacuum cleaner',
    free: false,
  },
  {
    group: 'ASMR',
    path: '../assets/ASMR/Triggers/Velcro_320.m4a',
    variantName: 'Velcro',
    sound: 'Triggers',
    free: false,
  },
  {
    group: 'Tweak',
    icon: 'fa-clock',
    path: '../assets/Tweak/Clocks_fa-clock/Wall Clock_320.m4a',
    variantName: 'Wall Clock',
    sound: 'Clocks',
    free: false,
  },
  {
    group: 'Tweak',
    icon: 'fa-clock',
    path: '../assets/Tweak/Clocks_fa-clock/Wall Clock 2_320.m4a',
    variantName: 'Wall Clock 2',
    sound: 'Clocks',
    free: false,
  },
  {
    group: 'Tweak',
    icon: 'fa-clock',
    path: '../assets/Tweak/Clocks_fa-clock/Wall Clock 3_320.m4a',
    variantName: 'Wall Clock 3',
    sound: 'Clocks',
    free: false,
  },
  {
    group: 'Tweak',
    icon: 'fa-clock',
    path: '../assets/Tweak/Clocks_fa-clock/Wall clock 4_320.m4a',
    variantName: 'Wall clock 4',
    sound: 'Clocks',
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-mountains',
    path: '../assets/Background/Waterfall_fa-mountains/Waterfall_320.m4a',
    variantName: 'Waterfall',
    sound: 'Waterfall',
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-mountains',
    path: '../assets/Background/Waterfall_fa-mountains/Waterfall 2_320.m4a',
    variantName: 'Waterfall 2',
    sound: 'Waterfall',
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-whale',
    path: '../assets/Others/Whale_fa-whale/Whale _320.m4a',
    variantName: 'Whale ',
    sound: 'Whale',
    free: true,
  },
  {
    group: 'Others',
    icon: 'fa-whale',
    path: '../assets/Others/Whale_fa-whale/Whale (Scary sound)_320.m4a',
    variantName: 'Whale (Scary sound)',
    sound: 'Whale',
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-whale',
    path: '../assets/Others/Whale_fa-whale/Whale 2_320.m4a',
    variantName: 'Whale 2',
    sound: 'Whale',
    free: false,
  },
  {
    group: 'Others',
    icon: 'fa-whale',
    path: '../assets/Others/Whale_fa-whale/Whale 3_320.m4a',
    variantName: 'Whale 3',
    sound: 'Whale',
    free: false,
  },
  {
    group: 'ASMR',
    path: '../assets/ASMR/Whisper/Whiser 2_320.m4a',
    variantName: 'Whiser 2',
    sound: 'Whisper',
    free: false,
  },
  {
    group: 'ASMR',
    path: '../assets/ASMR/Whisper/Whisper_320.m4a',
    variantName: 'Whisper',
    sound: 'Whisper',
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-wind',
    path: '../assets/Background/Wind_fa-wind/Whistling_320.m4a',
    variantName: 'Whistling',
    sound: 'Wind',
    free: false,
  },
  {
    group: 'Color noise',
    icon: 'fa-tv',
    path: '../assets/Color noise/White noise_fa-tv/White noise_320.m4a',
    variantName: 'White noise',
    sound: 'White noise',
    free: true,
  },
  {
    group: 'Tweak',
    icon: 'fa-music',
    path: '../assets/Tweak/Wind chimes_fa-music/Wind chimes_320.m4a',
    variantName: 'Wind chimes',
    sound: 'Wind chimes',
    free: true,
  },
  {
    group: 'Tweak',
    icon: 'fa-music',
    path: '../assets/Tweak/Wind chimes_fa-music/Wind chimes 2_320.m4a',
    variantName: 'Wind chimes 2',
    sound: 'Wind chimes',
    free: false,
  },
  {
    group: 'Tweak',
    icon: 'fa-music',
    path: '../assets/Tweak/Wind chimes_fa-music/Wind chimes 3_320.m4a',
    variantName: 'Wind chimes 3',
    sound: 'Wind chimes',
    free: false,
  },
  {
    group: 'Tweak',
    icon: 'fa-music',
    path: '../assets/Tweak/Wind chimes_fa-music/Wind chimes 4_320.m4a',
    variantName: 'Wind chimes 4',
    sound: 'Wind chimes',
    free: false,
  },
  {
    group: 'ASMR',
    icon: 'fa-hands-clapping',
    path: '../assets/ASMR/Tapping_fa-hands-clapping/Wood_320.m4a',
    variantName: 'Wood',
    sound: 'Tapping',
    free: false,
  },
  {
    group: 'ASMR',
    path: '../assets/ASMR/Triggers/Wood_320.m4a',
    variantName: 'Wood',
    sound: 'Triggers',
    free: false,
  },
  {
    group: 'ASMR',
    path: '../assets/ASMR/Triggers/Wood 2_320.m4a',
    variantName: 'Wood 2',
    sound: 'Triggers',
    free: false,
  },
  {
    group: 'ASMR',
    path: '../assets/ASMR/Triggers/Wood 3_320.m4a',
    variantName: 'Wood 3',
    sound: 'Triggers',
    free: false,
  },
  {
    group: 'ASMR',
    path: '../assets/ASMR/Triggers/Wood 4_320.m4a',
    variantName: 'Wood 4',
    sound: 'Triggers',
    free: false,
  },
  {
    group: 'ASMR',
    icon: 'fa-hands-clapping',
    path: '../assets/ASMR/Tapping_fa-hands-clapping/Wood(1)_320.m4a',
    variantName: 'Wood(1)',
    sound: 'Tapping',
    free: false,
  },
  {
    group: 'ASMR',
    path: '../assets/ASMR/Triggers/Wool_320.m4a',
    variantName: 'Wool',
    sound: 'Triggers',
    free: false,
  },
  {
    group: 'Tweak',
    icon: 'fa-clock',
    path: '../assets/Tweak/Clocks_fa-clock/Wrist watch_320.m4a',
    variantName: 'Wrist watch',
    sound: 'Clocks',
    free: false,
  },
  {
    group: 'Tweak',
    icon: 'fa-clock',
    path: '../assets/Tweak/Clocks_fa-clock/Wrist watch 2_320.m4a',
    variantName: 'Wrist watch 2',
    sound: 'Clocks',
    free: false,
  },
  {
    group: 'ASMR',
    path: '../assets/ASMR/Triggers/Writing pencil_320.m4a',
    variantName: 'Writing pencil',
    sound: 'Triggers',
    free: false,
  },
  {
    group: 'ASMR',
    path: '../assets/ASMR/Triggers/plastic bag_320.m4a',
    variantName: 'plastic bag',
    sound: 'Triggers',
    free: false,
  },
  {
    group: 'Background',
    icon: 'fa-cloud-showers-heavy',
    path: '../assets/Background/Rain_fa-cloud-showers-heavy/rain on the window_320.m4a',
    variantName: 'rain on the window',
    sound: 'Rain',
    free: false,
  },
] as ISoundItem[];

export default sounds;
